Repository dagati/teamcalendar, pull requests merged in 2022-03, with the labels that each got.

#2 Initialize project
  .github/workflows/build.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/datagi/teamcalendar/TeamcalendarApplication.java
  src/main/resources/application.properties
  src/test/java/com/datagi/teamcalendar/TeamcalendarApplicationTests.java
Labels: enhancement

#4 Update .gitignore
  .gitignore
Labels: enhancement

#6 Update build.yml
  .github/workflows/build.yml
Labels: bug

#10 (#9) Set package structure
  src/main/java/com/datagi/teamcalendar/domain/announcement/.gitkeep
  src/main/java/com/datagi/teamcalendar/domain/invitationcode/.gitkeep
  src/main/java/com/datagi/teamcalendar/domain/memberlist/.gitkeep
  src/main/java/com/datagi/teamcalendar/domain/participant/.gitkeep
  src/main/java/com/datagi/teamcalendar/domain/role/.gitkeep
  src/main/java/com/datagi/teamcalendar/domain/rolelist/.gitkeep
  src/main/java/com/datagi/teamcalendar/domain/schedule/.gitkeep
  src/main/java/com/datagi/teamcalendar/domain/team/.gitkeep
  src/main/java/com/datagi/teamcalendar/domain/user/.gitkeep
Labels: enhancement

#12 (#11) Create User entity
  build.gradle
  src/main/java/com/datagi/teamcalendar/domain/user/.gitkeep
  src/main/java/com/datagi/teamcalendar/domain/user/Authority.java
  src/main/java/com/datagi/teamcalendar/domain/user/User.java
  src/main/java/com/datagi/teamcalendar/domain/user/repository/UserRepository.java
  src/test/java/com/datagi/teamcalendar/user/UserTest.java
Labels: enhancement

#16 (#15) Fix CI
  .github/workflows/build.yml
  src/main/resources/application.yml
Labels: bug

#14 (#13) Create Announcement Entity
  src/main/java/com/datagi/teamcalendar/domain/announcement/.gitkeep
  src/main/java/com/datagi/teamcalendar/domain/announcement/Announcement.java
  src/main/java/com/datagi/teamcalendar/domain/announcement/repository/AnnouncementRepository.java
  src/test/java/com/datagi/teamcalendar/announcement/AnnouncementTest.java
Labels: enhancement

#20 (#19) Fix CI
  .github/workflows/build.yml
Labels: bug

#21 (#17) Refactor User
  src/main/java/com/datagi/teamcalendar/domain/user/User.java
  src/test/java/com/datagi/teamcalendar/user/UserTest.java
Labels: refactoring

#24 (#22) Create Team entity
  src/main/java/com/datagi/teamcalendar/domain/team/.gitkeep
  src/main/java/com/datagi/teamcalendar/domain/team/Team.java
  src/main/java/com/datagi/teamcalendar/domain/team/repository/TeamRepository.java
  src/test/java/com/datagi/teamcalendar/team/TeamTest.java
Labels: enhancement

#25 (#23) update announcement
  src/main/java/com/datagi/teamcalendar/domain/announcement/Announcement.java
  src/test/java/com/datagi/teamcalendar/announcement/AnnouncementTest.java
Labels: enhancement

#27 (#26) Create Schedule entity
  src/main/java/com/datagi/teamcalendar/domain/schedule/.gitkeep
  src/main/java/com/datagi/teamcalendar/domain/schedule/Schedule.java
  src/main/java/com/datagi/teamcalendar/domain/schedule/repository/ScheduleRepository.java
  src/test/java/com/datagi/teamcalendar/schedule/ScheduleTest.java
Labels: enhancement

#36 (#34) Create initial data for the test
  src/main/java/com/datagi/teamcalendar/domain/announcement/Announcement.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/java/com/datagi/teamcalendar/user/UserTest.java
Labels: enhancement
